api = "0.8"

[buildpack]
  id = "paketo-buildpacks/poetry-run"
  name = "Paketo Buildpack for Poetry Run"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"

[[targets.distros]]
name = "ubuntu"
version = "18.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"
