api = "0.8"

[buildpack]
  id = "paketo-buildpacks/poetry-run"
  name = "Paketo Poetry Run Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
